server:
  port: 3110
dubbo:
  registry:
    protocol: zookeeper
    address: 106.14.188.199:2181
  protocol:
    port: -1
    name: dubbo
  application:
    name: provider
  scan:
    base-packages: com.example.demo.service
logging:
  level:
    com:
      example:
        demo:
          provider: debug
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.14.188.199:3306/qingec_member?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: Sieyuan#1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 300
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: select 1 from dual


mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml