spring:
  application:
    name: stream_consumer
  rabbitmq:
    username : guest
    password: guest
    port: 5672
    host: localhost
  cloud:
    stream:
      bindings:
        input1 :
          destination: sieyuan
          group : boy
#          content-type : application/json
          content-type : text/plain
          stream_consumer:
            partitioned: true
        input2:
          destination: sieyuan
          group: girl
          content-type: application/json
          stream_consumer:
            partitioned: true
      instance-count: 2
      instance-index: 0
server:
  port: 9015
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
ribbon:
  eureka:
    enabled: true
logging:
  config:
    classpath: logback-spring.xml